algoritmo "comparar numeros"
var
    N1, N2:inteiro
inicio
      Escreva("Digite um número: ")
      Leia(N1)
      Escreva("Digite outro número: ")
      Leia(N2)
      se (N1 > N2) entao
         Escreva("O primeiro valor é maior")
      Senao
       se (N1 < N2) entao
         Escreva("O segundo valor é maior")
      senao
           Escreva("Os valores são iguais")
        fimse
      fimse
fimalgoritmo
