algoritmo "coversos de unidades de comprimento"
var
    N1,N2, N3, N4, N5, N6,N7:real
inicio
      Escreva("Digite uma distãncia em metros: ")
      Leia(N1)
      N2<- N1*10
      N3<- N1*100
      N4<- N1*1000
      N5<- N1/10
      N6<- N1/100
      N7<- N1/1000
      Escreval( "A distãncia de ",N1," m"," corresponde a : ")
      Escreval(N2," dm")
      Escreval(N3," cm")
      Escreval(N4," mm")
      Escreval(N5," dam")
      Escreval(N6," hm")
      Escreval(N7," km")

      
fimalgoritmo