algoritmo "semnome"
var
   N1, N2, N3, N4, N5, N6, N7, S:inteiro
inicio
      Escreval("Digite o 1 número: ")
      Leia(N1)
      Escreval("Digite o 2 número: ")
      Leia(N2)
      Escreval("Digite o 3 número: ")
      Leia(N3)
      Escreval("Digite o 4 número: ")
      Leia(N4)
      Escreval("Digite o 5 número: ")
      Leia(N5)
      Escreval("Digite o 6 número: ")
      Leia(N6)
      S <- N1 +N2 + N3 + N4 + N5 + N6
      Escreval(" A soma desses números é igua a ",S)
fimalgoritmo
